<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ArrowLeft, FileText, MessageSquareText, Search, ListTree, CheckCircle2, Send, Download, PanelLeft, ChevronRight } from '@lucide/vue'
import { useUiStore } from '../../stores/ui.js'
const router = useRouter(); const ui = useUiStore()
const stage = ref('input'); const topic = ref('矿井水资源化利用技术路线预研与产业应用分析'); const supplement = ref('重点比较膜分离、蒸发结晶与井下分级处理路线，关注高矿化度水质适配、能耗和工程案例。')
const activeProcess = ref(3); const tocOpen = ref(true)
const outline = ref(['研究背景与业务目标','国内外技术现状','关键技术路线与对比','产业应用与工程案例','风险、验证计划与建议','结论'])
const processes = ['理解研究目标','检索专利与论文','汇总技术路线','生成报告大纲']
</script>
<template>
  <section class="structured-workspace research-workspace">
    <header class="workspace-bar"><button type="button" @click="router.push('/agents')"><ArrowLeft :size="17" />智能应用首页</button><div><b>技术预研报告</b><span>研究主题 · 补充材料 · 大纲确认 · 报告</span></div><span class="status-chip info">{{ stage === 'report' ? '报告已生成' : '工作区自动保存' }}</span></header>
    <main v-if="stage === 'input'" class="report-input-page"><div class="input-intro"><i><FileText :size="28" /></i><span class="eyebrow">技术预研报告</span><h1>从研究主题和已有材料开始</h1><p>系统将检索授权专利、论文、政策与知识库资料，并先生成可编辑大纲。</p></div><label><span>研究主题</span><textarea v-model="topic" placeholder="输入技术预研主题" /></label><label><span>补充要求与已有材料</span><textarea v-model="supplement" placeholder="说明研究范围、对比路线、时间范围或已有结论" /></label><button class="button primary" type="button" @click="stage = 'outline'"><Search :size="18" />开始预研</button></main>
    <div v-else-if="stage === 'outline'" class="report-split-workspace"><aside class="research-process-panel"><header><span class="eyebrow">思考与检索过程</span><h1>{{ topic }}</h1></header><div class="process-timeline"><button v-for="(item,index) in processes" :key="item" :class="{ active: index === activeProcess, done: index < activeProcess }" @click="activeProcess = index"><i><CheckCircle2 v-if="index < activeProcess" :size="15" /><template v-else>{{ index + 1 }}</template></i><span><b>{{ item }}</b><small>{{ index < 3 ? '已完成并保留过程记录' : '等待用户确认' }}</small></span></button></div><footer><textarea placeholder="补充预研范围或要求" /><button aria-label="发送补充要求"><Send :size="18" /></button></footer></aside><main class="outline-workbench"><header><div><span class="eyebrow">报告大纲</span><h2>确认章节后生成完整报告</h2><p>大纲来源：研究主题、补充要求和已召回资料。最后两个章节支持重点修改。</p></div><span><ListTree :size="18" />6 个章节</span></header><div class="outline-editor detailed"><article v-for="(item,index) in outline" :key="index"><i>{{ String(index+1).padStart(2,'0') }}</i><input v-model="outline[index]" :readonly="index < 4" /><em>{{ index < 4 ? '系统生成' : '可修改' }}</em></article></div><footer><button class="button ghost" @click="stage = 'input'">返回修改输入</button><button class="button primary" @click="stage = 'report'">确认大纲并生成报告 <ChevronRight :size="17" /></button></footer></main></div>
    <div v-else class="generated-report-page"><aside v-if="tocOpen" class="report-toc"><header><ListTree :size="19" /><b>报告目录</b></header><button v-for="(item,index) in outline" :key="item" :class="{ active: index === 0 }">{{ index + 1 }}. {{ item }}</button></aside><main class="report-document"><header><button class="icon-button" title="显示或隐藏目录" @click="tocOpen = !tocOpen"><PanelLeft :size="19" /></button><div><span>技术预研报告</span><h1>{{ topic }}</h1><p>报告编号 RPT-260821-006 · 生成日期 2026-08-21</p></div><button class="button primary" @click="ui.notify('技术预研报告已生成 Word 文件','success')"><Download :size="17" />下载 Word</button></header><article><h2>1. 研究背景与业务目标</h2><p>围绕高矿化度矿井水资源化利用，系统检索并综合专利、论文、政策及内部项目资料，形成技术路线对比和工程验证建议。</p><h3>1.1 研究范围</h3><p>{{ supplement }}</p><div class="report-evidence-note"><MessageSquareText :size="19" /><span><b>引用依据 26 条</b><small>专利 8 条 · 论文 11 条 · 政策 3 条 · 内部资料 4 条</small></span></div><h2>2. 国内外技术现状</h2><p>现有路线主要包括膜分离、蒸发结晶、分级预处理和浓盐水协同处置。不同路线在进水水质、能耗、维护条件和副产物处置方面存在明显差异。</p></article></main></div>
  </section>
</template>
